[project]
name = 'Unified-Loyalty-Program-Aggregator'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.exchange]
path = 'contracts/exchange.clar'
clarity_version = 2
epoch = 2.5

[contracts.loyalty-program-registry]
path = 'contracts/loyalty-program-registry.clar'
clarity_version = 2
epoch = 2.5

[contracts.loyalty-token]
path = 'contracts/loyalty-token.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
